### PR TITLE
ENG-3003 Upgrade keycloak to version 15

### PR DESCRIPTION
**Pull request by alepintus**

### CODE REVIEW

**Review by cecchisandrone — APPROVED** [review]

**Comment by avdev4j** [comment]
Are the realm files have been checked? I know it's a bit hard to check everything there but upgrading for a large range of version can have some consequences there.

**Comment by cecchisandrone** [comment]
> Are the realm files have been checked? I know it's a bit hard to check everything there but upgrading for a large range of version can have some consequences there.

We checked that realm has been correctly imported during the very first Keycloack startup. Some import warnings have been spotted but they don't impact on the configuration integrity and can be addressed in the Entando 7.0 infrastructure upgrade scope

**Comment by avdev4j** [comment]
got it. I know these realms files can be hard to handle.

**Comment by avdev4j** [comment]
LGTM

**Review by avdev4j — APPROVED** [review]

**Pull request merged**
